#!/usr/bin/env zsh

setopt errexit
[[ -n $DEBUG ]] && setopt xtrace

trap 'print "$0:$LINENO failed with status $?" >&2' ZERR

here=$0:A:h
root=$here:h
builddir=$root/_build

[[ -z "$(git -C $root status --porcelain)" ]] || {
    read -q 'proceed?Root directory is dirty; proceed to deploy? [yN] ' || :
    print >&2
    [[ $proceed == y ]] || exit 1
}

[[ -z "$(git -C $builddir status --porcelain)" ]] || {
    read -q 'proceed?Build directory is dirty; proceed to deploy? [yN] ' || :
    print >&2
    [[ $proceed == y ]] || exit 1
}

git -C $builddir push origin master:master
